### ISSUE TITLE
Failed to launch (decky update)

### ISSUE THREAD

**Issue by PunkyBust** [metehankutlu/decky-save-manager#2]
Hello

SteamOS (stable) : 3.4.4
Decky Loader (stable) : 2.6.1

Thanks lot for this awsome tool, So much gain of time :) I love it !!
All was working perfectly but today
Save manager do not launch anymore since the Decky Update, I've abord this on Decky Loader Github [link](https://github.com/SteamDeckHomebrew/decky-loader/issues/379#issuecomment-1445435976)

I have this error :
![20230226_193538](https://user-images.githubusercontent.com/63625157/221429937-96eb0d6f-54c2-470b-9acb-b953e88722c6.jpg)

And after that, the whole DeckyLoader app disapear, need a steam restart to come again in the ui.

Try to fully remove DeckyLoader and force delete with sudo the residual file.
An clean installation do not resolve the issue.

Thanks.

**Comment by metehankutlu** [comment]
Hello

Thank you for your feedback. The plugin is still in progress and I'm working on it 👍
