### ISSUE TITLE
Evolutiln question

### ISSUE THREAD

**Issue by PunkyBust** [metehankutlu/decky-save-manager#3]
Hello,

So great Plugin, thank you for this job
Sorry I put not an issue but an question here.

Did you think it will be possible to backup folder and not just file ? Have the choice from both.
On some games we have multiple file link to your save state (out of user's parameters). For exemple recently Lies of P have 5 files. So I have to make 5 backup manually for only one game.
I will be so great to have this possibility

Have a good day 🙂

SteaomOS 3.6

**Comment by metehankutlu** [comment]
Hello, I've never thought about that actually but not a bad idea. I might add it as a feature in the next version. Thanks for the suggestion 👍
