### ISSUE TITLE
New decky loader breaks plugin

### ISSUE THREAD

**Issue by dc7707** [metehankutlu/decky-save-manager#6]
When trying to launch plugin in Decky version 2.11.1

I receive the error:
TypeError: Cannot read properties of undefined (reading 'SimpleModal')
at eval (eval at importReactPlugin (http://localhost:1337/frontend/chunk/-5ac6285.js:6900:43),  <anonymous:366:17)
at eval (eval at importReactPlugin (http://localhost:1337/frontend/chunk/-5ac6285.js:6900:43),  <anonymous:2848:3)
at PluginLoader.importReactPlugin (http://localhost:1337/frontend/chunk/-5ac6285.js:6900:43)
at async PluginLoader.importPlugin (http://localhost:1337/frontend/chunk/-5ac6285.js:6900:43)

**Comment by user31114** [comment]
same issue..

**Comment by sickhate** [comment]
Same

**Comment by ttang4299** [comment]
@metehankutlu Please migrate over to global DFL so that the plugins themselves do not break because of a SteamOS update, and the Decky devs can update the loader on their ends without needing the devs to update the plugins as well. I believe the Decky team should have more information about this global DFL.

**Comment by sickhate** [comment]
How does one migrate to dfl?

**Comment by ttang4299** [comment]
@sickhate I wouldn't know since this is something the plugin dev has to do himself. Migrating to global DFL means that any issue caused my future SteamOS updates should be fixed by the Decky team instead of each individual plugin needing to be updated every time an issue like this arises.

**Comment by sickhate** [comment]
Oh I see thanks for the explanation

**Comment by sickhate** [comment]
Been checking this plugin on a daily basis…
Please dont let this one die. 🙏🏽

**Comment by ttang4299** [comment]
@metehankutlu @metehan-kutlu Do you plan on moving this update to stable or keeping it on the testing version? The continued silence and hesitance to update the stable release is hurting your credibility, and the least you could do is appoint someone else who can maintain the plugin at a more reasonable pace.

**Comment by ttang4299** [comment]
@d3m3vilurr It seems no effort is going to be made to bring your fix to stable, so would you mind taking over as caretaker and letting Decky admin know so they can switch to your fork?
